// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/contracts/verification-tokens-repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/contracts/verification-tokens-repository.go -destination=test/mocks/verification-tokens-repository-mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/henrique998/go-auth/internal/app/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationTokensRepository is a mock of VerificationTokensRepository interface.
type MockVerificationTokensRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokensRepositoryMockRecorder
}

// MockVerificationTokensRepositoryMockRecorder is the mock recorder for MockVerificationTokensRepository.
type MockVerificationTokensRepositoryMockRecorder struct {
	mock *MockVerificationTokensRepository
}

// NewMockVerificationTokensRepository creates a new mock instance.
func NewMockVerificationTokensRepository(ctrl *gomock.Controller) *MockVerificationTokensRepository {
	mock := &MockVerificationTokensRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokensRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationTokensRepository) EXPECT() *MockVerificationTokensRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVerificationTokensRepository) Create(vt entities.VerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", vt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerificationTokensRepositoryMockRecorder) Create(vt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationTokensRepository)(nil).Create), vt)
}

// Delete mocks base method.
func (m *MockVerificationTokensRepository) Delete(tokenId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVerificationTokensRepositoryMockRecorder) Delete(tokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVerificationTokensRepository)(nil).Delete), tokenId)
}

// FindByValue mocks base method.
func (m *MockVerificationTokensRepository) FindByValue(val string) *entities.VerificationToken {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByValue", val)
	ret0, _ := ret[0].(*entities.VerificationToken)
	return ret0
}

// FindByValue indicates an expected call of FindByValue.
func (mr *MockVerificationTokensRepositoryMockRecorder) FindByValue(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByValue", reflect.TypeOf((*MockVerificationTokensRepository)(nil).FindByValue), val)
}
