POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/accounts
content-type: application/json

{
  "name": "henrique",
  "email": "henriquemonteiro037@gmail.com",
  "password": "123456",
  "phone": "99999999"
}

###

POST https://3333-henrique998-goauth-8h49qimho84.ws-us115.gitpod.io/session/login
content-type: application/json

{
  "email": "henriquemonteiro037@gmail.com",
  "password": "herozero10"
}

### 

POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/refresh-token
content-type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmVkNmVkMS00ZDY2LTQ4ZDYtOWM2Zi0zMjAzMzgxNDUwYzgiLCJleHAiOjE3MjA1MjgzODB9.q-O6VkENNXHCOypTXlNCOLNtYAtnMfeE2GCSGKJ6yzU"
}

### 

POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/session/logout

### 

POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/accounts/send-2fa-code

###

POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/accounts/verify-2fa-code
content-type: application/json

{
  "code": "74a752002f5688f2ba9a"
}

###

POST https://3333-henrique998-goauth-8h49qimho84.ws-us115.gitpod.io/accounts/send-new-pass-request
content-type: application/json

{
  "email": "henriquemonteiro037@gmail.com"
}

###

PUT https://3333-henrique998-goauth-8h49qimho84.ws-us115.gitpod.io/accounts/update-pass
content-type: application/json

{
  "code": "cae60bafbd770665ee57",
  "newPass": "herozero10",
  "newPassConfirmation": "herozero10"
}

###

GET https://3333-henrique998-goauth-8h49qimho84.ws-us115.gitpod.io/session/google/redirect

###

POST https://3333-henrique998-goauth-8h49qimho84.ws-us115.gitpod.io/session/login/google
content-type: application/json

{
  "code": "4/0AcvDMrBb8ROYDbQa64NQHp6lz_ko7EXEwKxVZzm8NdnCP3HvI5zQFJtksMYFVyG9kO-Obw"  
}

###

POST https://3333-henrique998-goauth-8h49qimho84.ws-us115.gitpod.io/session/magic-link/request
content-type: application/json

{
  "email": "henriquemonteiro037@gmail.com"  
}

###

GET https://3333-henrique998-goauth-8h49qimho84.ws-us115.gitpod.io/accounts/devices