POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/users
content-type: application/json

{
  "name": "henrique",
  "email": "henrique@gmail.com",
  "password": "123456",
  "phone": "99999999"
}