POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/accounts
content-type: application/json

{
  "name": "henrique",
  "email": "henriquemonteiro037@gmail.com",
  "password": "123456",
  "phone": "99999999"
}

###

POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/login
content-type: application/json

{
  "email": "henriquemonteiro037@gmail.com",
  "password": "123456"
}

### 

POST https://3333-henrique998-goauth-8h49qimho84.ws-us114.gitpod.io/refresh-token
content-type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmVkNmVkMS00ZDY2LTQ4ZDYtOWM2Zi0zMjAzMzgxNDUwYzgiLCJleHAiOjE3MjA1MjgzODB9.q-O6VkENNXHCOypTXlNCOLNtYAtnMfeE2GCSGKJ6yzU"
}